server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://tgather:8761/eureka


spring:
  application:
    name: gateway-service
  profiles:
    active:
      on-profile: dev
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus