server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://tgather:8761/eureka


spring:
  application:
    name: gateway-service
  profiles:
    active:
      on-profile: dev
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://127.0.0.1:3000
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods: "*"
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus