server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/actuator/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/account/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}
            - JwtAuthenticationTokenFilter

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Filter
            preLogger: true
            postLogger: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus